topics:
  - name    : joy
    topic   : joy_teleop/cmd_vel
    timeout : 0.5
    priority: 9
  - name    : bt_joy
    topic   : bluetooth_teleop/cmd_vel
    timeout : 0.5
    priority: 10 
  - name    : interactive_marker
    topic   : twist_marker_server/cmd_vel
    timeout : 0.5
    priority: 8
  - name    : external
    topic   : cmd_vel
    timeout : 0.5
    priority: 1
  - name    : con_vel
    topic   : con_vel
    timeout : 0.5
    priority: 12

locks:
  - name    : e_stop
    topic   : e_stop
    timeout : 0.0
    priority: 255

